# Generated by Django 5.2.4 on 2025-07-24 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectidea",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectidea",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.category",
            ),
        ),
        migrations.AddField(
            model_name="projectidea",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectlike",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="projects.projectidea",
            ),
        ),
        migrations.AddField(
            model_name="projectlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectstats",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="projects.projectidea",
            ),
        ),
        migrations.AddField(
            model_name="projecttag",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.projectidea"
            ),
        ),
        migrations.AddField(
            model_name="projectview",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="projects.projectidea",
            ),
        ),
        migrations.AddField(
            model_name="projectview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projecttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.tag"
            ),
        ),
        migrations.AddField(
            model_name="projectidea",
            name="tags",
            field=models.ManyToManyField(
                related_name="projects",
                through="projects.ProjectTag",
                to="projects.tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectlike",
            unique_together={("project", "user")},
        ),
        migrations.AddIndex(
            model_name="projectview",
            index=models.Index(
                fields=["project", "-created_at"], name="project_vie_project_8ded35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectview",
            index=models.Index(
                fields=["ip_address", "session_id"],
                name="project_vie_ip_addr_5d50cc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projecttag",
            unique_together={("project", "tag")},
        ),
        migrations.AddIndex(
            model_name="projectidea",
            index=models.Index(
                fields=["status", "-created_at"], name="project_ide_status_df5df9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectidea",
            index=models.Index(
                fields=["category", "status"], name="project_ide_categor_27fcfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectidea",
            index=models.Index(
                fields=["difficulty", "status"], name="project_ide_difficu_becbd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectidea",
            index=models.Index(
                fields=["is_featured", "status"], name="project_ide_is_feat_6c666a_idx"
            ),
        ),
    ]
