# Generated by Django 5.2.4 on 2025-07-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("messages", models.PositiveIntegerField(default=0)),
                ("direct_traffic", models.PositiveIntegerField(default=0)),
                ("search_traffic", models.PositiveIntegerField(default=0)),
                ("social_traffic", models.PositiveIntegerField(default=0)),
                ("referral_traffic", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "project_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("category_filter", models.CharField(blank=True, max_length=100)),
                ("difficulty_filter", models.CharField(blank=True, max_length=50)),
                ("tags_filter", models.JSONField(blank=True, default=list)),
                ("clicked_results", models.JSONField(blank=True, default=list)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_queries",
            },
        ),
        migrations.CreateModel(
            name="TrendingProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("day", "Daily"),
                            ("week", "Weekly"),
                            ("month", "Monthly"),
                            ("year", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("trend_score", models.FloatField()),
                ("views_growth", models.FloatField(default=0.0)),
                ("likes_growth", models.FloatField(default=0.0)),
                ("comments_growth", models.FloatField(default=0.0)),
                ("rank", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trending_projects",
                "ordering": ["timeframe", "rank"],
            },
        ),
        migrations.CreateModel(
            name="UserEngagementMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("login_count", models.PositiveIntegerField(default=0)),
                ("projects_viewed", models.PositiveIntegerField(default=0)),
                ("projects_liked", models.PositiveIntegerField(default=0)),
                ("comments_posted", models.PositiveIntegerField(default=0)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("search_queries", models.PositiveIntegerField(default=0)),
                ("session_duration", models.PositiveIntegerField(default=0)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_engagement_metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PlatformStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("total_projects", models.PositiveIntegerField(default=0)),
                ("published_projects", models.PositiveIntegerField(default=0)),
                ("new_projects", models.PositiveIntegerField(default=0)),
                ("total_comments", models.PositiveIntegerField(default=0)),
                ("new_comments", models.PositiveIntegerField(default=0)),
                ("total_likes", models.PositiveIntegerField(default=0)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("category_stats", models.JSONField(blank=True, default=dict)),
                ("trending_tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "platform_statistics",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
    ]
