# Generated by Django 5.2.4 on 2025-07-24 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0002_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trendingproject",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trending_records",
                to="projects.projectidea",
            ),
        ),
        migrations.AddField(
            model_name="userengagementmetrics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagement_metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectanalytics",
            unique_together={("project", "date")},
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["query", "-created_at"], name="search_quer_query_1bea7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["user", "-created_at"], name="search_quer_user_id_486cee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["-created_at"], name="search_quer_created_824a49_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trendingproject",
            unique_together={("project", "timeframe", "period_start")},
        ),
        migrations.AlterUniqueTogether(
            name="userengagementmetrics",
            unique_together={("user", "date")},
        ),
    ]
